# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='entry_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
