# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170616_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='gamethread_ident',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
