# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_party_gamethread_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='gamethread_ident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
